title: Gregoire Guillet
description: Research Scientist - Applied mathematics for the cryosphere — University of Oslo
url: "https://gregguillet.github.io"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
