title: Gregoire Guillet
description: Research scientist at the University of Oslo
url: "https://gregguillet.github.io"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
navigation:
  - title: Home
    url: /
  - title: Research
    url: /research
  - title: Publications
    url: /publications
  - title: About me
    url: /about

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .bundle/
